### ISSUE TITLE
Copilot chat fails when called from a window where foldmethod is not manual

### ISSUE THREAD

**Issue by kristofka** [jellydn/CopilotChat.nvim#56]
### Describe the bug

Running `CopilotChat` when the default `foldmethod` is not manual results in the following error : 
```
Traceback (most recent call last):
  File "/Users/***/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/copilot-plugin.py", line 39, in copilot_agent_visual_cmd
    self.vsplit_chat_handler.chat(args[0], file_type, code)
  File "/Users/***/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/handlers/vsplit_chat_handler.py", line 38, in chat
    super().chat(prompt, filetype, code, self.nvim.current.window.handle)
  File "/Users/***/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/handlers/chat_handler.py", line 48, in chat
    self._add_start_separator(system_prompt, prompt, code, filetype, winnr)
  File "/Users/***/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/handlers/chat_handler.py", line 79, in _add_start_separator
    self._add_start_separator_with_token_count(
  File "/Users/***/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/handlers/chat_handler.py", line 160, in _add_start_separator_with_token_count
    self._add_folds(code, code_height, last_row_before, system_prompt_height, winnr)
  File "/Users/***/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/handlers/chat_handler.py", line 176, in _add_folds
    self.nvim.command(full_command)
  File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/pynvim/api/nvim.py", line 311, in command
    return self.request('nvim_command', string, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/pynvim/api/nvim.py", line 199, in request
    res = self._session.request(name, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/pynvim/msgpack_rpc/session.py", line 139, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(fold):E350: Cannot create fold with current 'foldmethod'
``` 
The culprit seems to be at the line referenced here : 

https://github.com/jellydn/CopilotChat.nvim/blob/405598454408bd8998851a7bfcf39543b91c6d1c/rplugin/python3/handlers/chat_handler.py#L174

adding 
```python
        self.nvim.command("set foldmethod=manual")
```
before this line seems to fix the issue, although I don't know wether it's generally a good approach.

### Reproduction

`:set foldmethod` returns `foldmethod=expr` , CopilotChat crashes

### System Info

```Shell
neovim main branch, CopilotChat.nvim main branch
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jellydn** [comment]
Thanks, @kristofka for your report. Could you open PR about the workaround as you mentioned? I also asked other maintainer but we haven't got any better solution here.
